### ISSUE TITLE
Null Pointer Exception during grounding

### ISSUE THREAD

**Issue by femigr** [domschrei/aquaplanning#13]
Using the minimum example provided below, the following output is put out by Aquaplanning.
I believe it is caused by Operator.setEffect(AbstractCondition) not being called with a valid condition.
```
java -jar ./target/aquaplanning-0.0.1-SNAPSHOT-jar-with-dependencies.jar files/rubikscube/domainminimumproblem.pddl files/rubikscube/problemminimumproblem.pddl 
This is Aquaplanning - QUick Automated Planning.
Parsing ...
Parsing complete.

Grounding ...
An error occurred.
java.lang.NullPointerException
	at edu.kit.aquaplanning.grounding.Preprocessor.instantiateQuantifications(Preprocessor.java:137)
	at edu.kit.aquaplanning.grounding.Preprocessor.simplifyProblem(Preprocessor.java:91)
	at edu.kit.aquaplanning.grounding.Preprocessor.preprocess(Preprocessor.java:58)
	at edu.kit.aquaplanning.grounding.RelaxedPlanningGraphGrounder.ground(RelaxedPlanningGraphGrounder.java:42)
	at edu.kit.aquaplanning.Main.main(Main.java:99)
```

[MinimumExample.zip](https://github.com/domschrei/aquaplanning/files/2769227/MinimumExample.zip)

**Comment by domschrei** [comment]
Thanks. The problem was that "empty" preconditions and effects only worked by writing
`(:precondition (and ))`, but not by writing `(:precondition ())` or omitting the whole precondition/effect expression. This is now fixed in the parser, and should work in the other cases as well.
