### ISSUE TITLE
Expose faulty element when AST Parsing throws an Exception

### ISSUE THREAD

**Issue by MeFisto94** [domschrei/aquaplanning#27]
So, I'm generally new to planning, so I probably ran a faulty domain file, but it passed the parser stage and crashed during AST Walking.

Now it's hard to see which statement caused the error and thus (if possible) it would be awesome to have a resolution from AST Element -> Source Line/Column. In it's current state I only know that my "FHead" is missing some types, but unfortunately that doesn't help me much.

For reference, here's the problem:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at edu.kit.aquaplanning.parsing.ProblemParser.enterFHead(ProblemParser.java:996)
        at edu.kit.aquaplanning.parsing.PddlHtnParser$FHeadContext.enterRule(PddlHtnParser.java:3247)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at edu.kit.aquaplanning.parsing.ProblemParser.parse(ProblemParser.java:173)
        at edu.kit.aquaplanning.Main.main(Main.java:98)
```

Domain:
```pddl
; Numeric planning in practice is rather limited, because planners are limited, even though the spec is not.
; One of these issues is the cost optimization. For Fast-Downward, the cost metric needs to be called "total-cost"
; This domain used "total-distance" before, but apparently that is as illegal as using ":fluents" in the requirements
(define (domain mail)
    (:requirements :typing :negative-preconditions :equality :action-costs) ; Other synonyms for action costs  :numeric-fluents :fluents :action-costs)

    (:types location - object
            letter - object
    )

    (:constants mailbox - location)

    (:predicates
        (at ?l - location); If the Salesman is at the given location
        (canDropAt ?let - letter ?loc - location) ; Can the given letter be dropped at the location loc.
        ; this even allows us to drop letters at various locations
        (deliver ?let - letter) ; Used for the goal "deliver all letters".
        (batched ?let - letter) ; TODO: Use to simulate the stack.
    )

    (:functions
        (distance ?from ?to) - number
        ; Fast-Downward accepted (batch-count) without anything, but this seems to be the official form.
        (batch-count) - number
        (total-cost) - number
    )

    (:action goto
        :parameters (?from - location ?to - location)
        :precondition (and
            (at ?from)
            (not(at ?to)) ; Prevent useless loops/from == to
        )
        :effect (and
            (at ?to)
            (not (at ?from))
            (increase (total-cost) (distance ?from ?to))
        )
    )

    ; This is explicitly modelled, so that we can model things like recharging pauses
    ; TODO: Currently there is no modelling of the stack content, and as such, this method won't be used yet.
    ; The Planner has no reason to pick up letters.
    (:action pickup
        :parameters (?let - letter)
        :precondition (and
            (at mailbox)
            ; TODO: The following line is not supported by fast downward
            (<= (batch-count) 5)
        )
        :effect (and
            ; TODO: The following line is not supported by fast downward
            (increase (batch-count) 1)
        )
    )

    (:action drop
        :parameters (?let - letter ?loc - location)
        :precondition (and
            (at ?loc)
            (canDropAt ?let ?loc)
            ; TODO: The following line is not supported by fast downward
            (> (batch-count) 0)
        )
        :effect (and
            (deliver ?let)
            ; TODO: The following line is not supported by fast downward
            (decrease (batch-count) 1)
        )
    )
)
```

Thanks in Advance!

**Comment by MeFisto94** [comment]
I could fix this, the issue was `(distance ?from ?to) - number`, it has to be `(distance ?from - location ?to - location) - number`.
I wonder why `VAL` (the validator) also makes this pass the syntax check, much like AquaPlanning.

I guess AquaPlanning should either assert that behavior or maybe change the grammar accordingly.
